"""empty message

Revision ID: 0711df71015a
Revises: 
Create Date: 2018-03-20 13:05:02.847575

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0711df71015a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
