"""empty message

Revision ID: 583c49183392
Revises: e7493a2115c7
Create Date: 2018-03-26 16:38:58.865493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '583c49183392'
down_revision = 'e7493a2115c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', mysql.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
