"""empty message

Revision ID: 713fb9ed2b15
Revises: 0711df71015a
Create Date: 2018-03-21 14:25:09.017401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713fb9ed2b15'
down_revision = '0711df71015a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'img_path')
    # ### end Alembic commands ###
