"""empty message

Revision ID: 9d7e6c2b0d8c
Revises: 713fb9ed2b15
Create Date: 2018-03-21 14:34:00.939826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7e6c2b0d8c'
down_revision = '713fb9ed2b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('img_path', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
