"""empty message

Revision ID: c0fba4e6d887
Revises: 9d7e6c2b0d8c
Create Date: 2018-03-21 17:32:27.442599

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c0fba4e6d887'
down_revision = '9d7e6c2b0d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('img_path', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
