"""empty message

Revision ID: d14f9a66b7a6
Revises: c0fba4e6d887
Create Date: 2018-03-21 17:47:40.742837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14f9a66b7a6'
down_revision = 'c0fba4e6d887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'isstar')
    # ### end Alembic commands ###
