"""empty message

Revision ID: d44917cd8149
Revises: d14f9a66b7a6
Create Date: 2018-03-25 17:43:48.867004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44917cd8149'
down_revision = 'd14f9a66b7a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'reply')
    # ### end Alembic commands ###
